# Generated by Django 2.1 on 2018-08-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultureAndRecreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('release_year', models.IntegerField()),
                ('location', models.CharField(max_length=2000)),
                ('fun_fact', models.TextField()),
                ('production_company', models.CharField(max_length=2000)),
                ('distributor', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=500)),
                ('actor1', models.CharField(max_length=100)),
                ('actor2', models.CharField(max_length=100)),
                ('actor3', models.CharField(max_length=100)),
            ],
        ),
    ]
