# Generated by Django 2.1 on 2018-08-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('api_name', models.CharField(max_length=500)),
                ('memory', models.FloatField(default=0)),
                ('vcpu', models.IntegerField(blank=True, null=True)),
                ('internal_storage', models.TextField()),
                ('network_performance', models.CharField(blank=True, max_length=500, null=True)),
                ('linux_on_demand_cost', models.FloatField(blank=True, default=0, null=True)),
                ('linux_reserved_cost', models.FloatField(blank=True, default=0, null=True)),
                ('windows_on_demand_cost', models.FloatField(blank=True, default=0, null=True)),
                ('windows_reserved_cost', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
