# Generated by Django 2.1 on 2018-08-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec2instance',
            old_name='internal_storage',
            new_name='instance_storage',
        ),
    ]
