# Generated by Django 2.1 on 2018-08-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultureandrecreation',
            name='director',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='actor1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='actor2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='actor3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='distributor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='location',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='production_company',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cultureandrecreation',
            name='writer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
