# Generated by Django 2.1 on 2018-08-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_task', '0002_auto_20180829_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='api_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='instance_storage',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
